### ISSUE TITLE
Broken link for Bengali, Hindi and Tamil

### ISSUE THREAD

**Issue by rohandas14** [gorka96/Coreference-Corpora-List#2]
It seems like the links for the corpora for Indian languages are broken. Have these resources been withdrawn by the owners? I don't see them being listed on the website.

**Comment by GorkaUrbizu** [comment]
Thanks for reporting it. 
But sadly I can't do much since I couldn't find the ICON-2011 resource anywhere else. I will keep the broken link to see if they fix it soon, and otherwise I'll replace it with a link to a paper, [Anaphora Resolution for Bengali, Hindi, and Tamil Using RandomTree Algorithm in Weka](https://d1wqtxts1xzle7.cloudfront.net/31118274/report_iitkgp_final-with-cover-page-v2.pdf?Expires=1668166611&Signature=fVwc~NHcHmOFI4TEEoBmiveQhZihajuvj0j1wIU5f~3zkzniWBMiXcvZ6-j9Te9uCoT4unR-YhWRhFlEBWn~oq7XSDcSZUkZi7GoquxvcClwFcEeD51BQ9LHJP69j3opkPjZA-o6EacHEpQJ07bPyznRmIDgtTaXAoL67Mfb5xTkS0d6Z3HHWSIeirxtq1S-vYcVS1CKU53t3HsCPrlZvRWq3pi9RCu88g1cR9xTqSHW~TJymrY1lPC2Bnh1pLBDvJvwZ4ch7FZ6e6Ujb-6jPpFGWdjuPShUK~kofd~uO8lq5u4vutFtFglDi6JS012MTanDCZaOd32hpNMda0juag__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA) so at least someone could reach the author to ask about the resource

**Comment by rohandas14** [comment]
Thanks for clarifying. I'll try to reach out to the authors and will post an update here if I hear back from them.

**Comment by GorkaUrbizu** [comment]
@rohandas14 Thanks

**Comment by GorkaUrbizu** [comment]
@rohandas14 any update? otherwise I will change the broken link to the paper

**Comment by rohandas14** [comment]
@GorkaUrbizu Apologies, but I never got around to contacting the authors since I ended up going with a different dataset that fit my needs better.

**Comment by GorkaUrbizu** [comment]
@rohandas14 great. I will change the broken link with the paper then.
